### ISSUE TITLE
laminas?

### ISSUE THREAD

**Issue by markushausammann** [JouwWeb/SlmMail#121]

**Comment by aimfeld** [comment]
Now Zend made it's transition to Laminas the packages should to be updated to point to the correct new packages. This might help: https://github.com/laminas/laminas-migration

**Comment by aimfeld** [comment]
@bakura10 Could you please create a release, so we can start using the Laminas version of SlmMail? That would be awesome, thanks for the great work!

**Comment by bakura10** [comment]
Hi @aimfeld,

It's been ages I didn't have a look at this page. I can see the management have been moved to another organization, it seems I still have rights to tag, but as it has moved to another organization I susppose it would be better if it would be maintained by someone else?

**Comment by aimfeld** [comment]
@roelvanduijnhoven Could you tag a release if possible? Thanks!

**Comment by roelvanduijnhoven** [comment]
@bakura10 I removed you as contributor, as I think that is what you meant with your comment :). If you _do_ want to keep participating, let me know: and I'll add you again!
