### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by aimfeld** [JouwWeb/SlmMail#127]
Could anyone tag a release? The latest one is from May 2017 and it would be great to be able to use the Laminas version of SlmMail. Thanks!

**Comment by roelvanduijnhoven** [comment]
@aimfeld We first need to test the library before we do so. The master as-is is probably not production ready.

Furthermore: I'd also like to limit support to the next major version tot PHP >= 7.2. As we are increasing a major version, this is the time to do so :).

Did you already test the library yourself on your project? If so: did it work? If not: would you be willing to test it, and give feedback on the current state?

Thanks!

**Comment by aimfeld** [comment]
@roelvanduijnhoven We have used SlmMail for years, using the Postmark Service. We have recently upgraded our codebase to Laminas and PHP 7.4, and SlmMail (version 2.1.2) still works for us. I will test the SlmMail master asap and let you know! Thanks for providing this great module 👍

**Comment by roelvanduijnhoven** [comment]
@aimfeld I'll await your feedback before I will test it myself. Let me know what you find!

**Comment by aimfeld** [comment]
@roelvanduijnhoven I was able to send a test e-mail using the Postmark service with the SlmMail master. Looks like things are working fine 👍

**Comment by roelvanduijnhoven** [comment]
@aimfeld I did some work towards releasing a new version. Could you test out the v3.0-alpha release?

**Comment by aimfeld** [comment]
@roelvanduijnhoven Sorry for the delay, I tested v3.0 and it works for us 👍
