### ISSUE TITLE
Asynchronous API 

### ISSUE THREAD

**Issue by ojhaujjwal** [JouwWeb/SlmMail#76]
With the evolution of [react](https://github.com/reactphp/react), it's time now to think about creating asynchronous API.

``` php
$transport->send($message)
    ->then(
        function() {
            // message is sent, lets rock the world
        },
        function(\Exception $e) {
           // error sending message
        }
    );
```

**Comment by roelvanduijnhoven** [comment]
I don't think we will be implement something like this.

A solution would be to use a queueing system (see [SlmQueue](https://github.com/JouwWeb/SlmQueue)) to send the mail in the background.

Will close this.
